### ISSUE TITLE
Search results component

### ISSUE THREAD

**Issue by amihaiemil** [opencharles/charles-search-box#2]
A component that will render paginated search results is needed.

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index pls

**Comment by charlesmike** [comment]
> @charlesmike index pls

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository's name must match the format `owner.github.io` or it must have a project website on branch `gh-pages`

**Comment by amihaiemil** [comment]
ok

**Comment by amihaiemil** [comment]
done
