### ISSUE TITLE
Decent default styling

### ISSUE THREAD

**Issue by amihaiemil** [opencharles/charles-search-box#8]
Clients should have the option to include their own styles, based on the classes and ids used on the components but also, a decent-looking default styling should be offered. One that should fit the most website layouts, (as "transparent" and fitting in as possible)

Look here: https://github.com/opencharles/charles-search-box#build
for info on how to build and run the widget on your machine.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by amihaiemil** [comment]
@charlesmike hi

**Comment by charlesmike** [comment]
> @charlesmike hi

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@charlesmike index

**Comment by charlesmike** [comment]
> @charlesmike index

@amihaiemil the repository's name must match the format ``owner.github.io`` or it must have a project website on branch ``gh-pages``

**Comment by amihaiemil** [comment]
@charlesmike hi there

**Comment by charlesmike** [comment]
> @charlesmike hi there

Hi, @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

**Comment by amihaiemil** [comment]
@kaymorey Please do the changes on a branch named 8 (after the ticket number) and make a PR when you're done. Thanks!
